name: Build and Deploy Flutter Web to Netlify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: stable
          cache: true

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Create app_secrets.dart
        shell: bash
        run: |
          mkdir -p lib/core/secrets
          cat > lib/core/secrets/app_secrets.dart <<'EOF'
          class AppSecrets {
            // Environment configuration
            static const bool isProduction = true;

            // Supabase configuration (safe for all platforms)
            static const String supabaseUrl = "${{ secrets.SUPABASE_URL }}";
            static const String supabaseAnonKey = "${{ secrets.SUPABASE_ANON_KEY }}";
            static const String backendUrl = "${{ secrets.BACKEND_URL }}";
          }
          EOF

      - name: Build Flutter Web
        run: flutter build web --release --web-renderer canvaskit

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: build/web
          production-deploy: true
        env:

          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
